[정수론] 9월 6일
Altu-Bitu-5/Altu-Bitu-KimEunsom pull request #2
Opened 2023-09-06 09:41 UTC by kimeunsom

### 인적사항
학번:2271018
이름:김은솜
</br>

### 과제제출
기존 제출: 2840, 6588, 1735
추가 제출:
</br>

2023-09-09 17:03 UTC, kimhj010502 requested changes
**[정수론 구현 문제 코드 리뷰 완료]**

2840(P1)

은솜님 안녕하세요!
백준에서 "맞았습니다"가 나오는 문제만 과제 제출로 인정해드립니다.
몇 가지 피드백 드렸으니 참고해서 다시 제출해주세요!
궁금한 점이 있으면 리뷰어를 호출해주세요!

+) Pull Request에 1, 2주차 코드도 포함되어있네요 과제 제출 방법을 다시 한 번 확인해주세요!

2023-09-09 17:03 UTC, kimhj010502 commented on 03_정수론/2840.cpp
> +
P1. 알파벳의 중복을 확인해주는 코드가 없어서 백준에서 돌아가지 않네요. 이 경우에는 과제가 미제출처리되니 다시 확인해주세요!

2023-09-11 05:04 UTC, kwakrhkr59 reviewed
**[정수론 알고리즘 코드 리뷰 완료]**
6588(P2) 안녕하세요 은솜님~ 정수론 필수 알고리즘 문제 코드리뷰 완료되셨습니다! 몇가지 코멘트 남겨드렸습니다 확인해보시고 질문 있으시면 언제든 리뷰어로 호출해주세요😊 수고 많으셨습니다~

2023-09-11 05:04 UTC, kwakrhkr59 commented on 03_정수론/6588.cpp
> +    vector<bool> is_prime(1000001, true);
P2. 전역변수의 활용은 최대한 자제해주세요! 전역변수는 굳이 함수에 인자로 넣어주지 않아도 된다는 장점도 있지만, 한 번 수정될 경우 코드 전체에 영향을 미칠 수 있다는 위험성도 가지고 있죠😢 전역변수는 함수 3개 이상에서 공통적으로 사용되는 경우에만 사용해주시고 지금과 같은 경우에는 함수 안에서 지역변수로 선언한 후 인자값으로 전달해주시는 식으로 바꿔주시면 좋을 것 같습니다😊

2023-09-11 05:04 UTC, kwakrhkr59 commented on 03_정수론/6588.cpp
> +    for(int i=2; i<=1000001; i++) {
1000001이라는 숫자는 입력 범위를 의미하는 숫자죠! 이 숫자는 반복해서 사용되고 있기도 하고 특정한 의미를 가지고 있기도 하죠? 이런 경우에는 상수로 선언해주시면 훨씬 더 의미를 명확하게 전달할 수도 있고 코드도 더 깔끔해질 것 같네요😁

2023-09-11 05:04 UTC, kwakrhkr59 commented on 03_정수론/6588.cpp
> +            }
이미 false인지 따로 판단해주지 않으셔도 될 것 같습니다!

2023-09-19 05:38 UTC, merged