04 브루트포스
Altu-Bitu-5/Altu-Bitu-KimEunsom pull request #3
Opened 2023-09-13 09:53 UTC by kimeunsom

###인적사항
학번:2271018
이름:김은솜

###과제제출
기존 제출: 1052, 14620, 1063, 11723, 1436
추가 제출:

2023-09-15 14:46 UTC, Goldchae approved these changes
**브루트 포스- 구현 문제 리뷰 완료!**
p3. 깔끔하게 잘 작성해주신 것 같습니다! 수고하셨어요!

2023-09-15 14:46 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +            k[0]--;
p3. 두개의 문자로 이루어진 방향표시는 각각 알파벳 두 개의 방향표시로 나누어 생각할 수 있죠! 코드를 줄일 방법은 없을까요?

2023-09-15 14:46 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +int main()
가벼운 메인 함수 좋습니다!

2023-09-15 14:46 UTC, Goldchae commented on 04_브루트포스/1063.cpp
> +        if(k[0]<'A' || k[0]>'H' || k[1]<'1' || k[1]>'8') {
char 형을 이용해서 연산 진행해 주신 것 좋습니다!

2023-09-17 11:05 UTC, kwakrhkr59 requested changes
**브루트포스 필수 알고리즘 코드 리뷰 완료**
14620(P1) 안녕하세요 은솜님~ 브루트포스 필수 및 도전 문제 코드리뷰 완료되셨습니다! 다만 14620 문제에서 제출해주신 코드가 백준에서 통과되고 잇지 않는 것으로 보입니다😥 코드를 제출해주셔도 백준에서 통과했습니다가 뜨지 않으면 과제 제출로 인정되지 않으니 반드시 확인 후 재제출해주시고, 재제출하신 뒤 리뷰어로 호출해주시면 제가 확인 후 과제 제출 인정해드리도록 하겠습니다😊

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/11723.cpp
> +            ans = (1 << 21) - 1;
의미를 명확히 하기 위해서 `const int ALL = (1 << 21) - 1`로 선언한 후 `ans = ALL`등으로 사용해주는 건 어떨까요?

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/1436.cpp
> +            if(temp%1000==NUM) { //끝자리 666이면 카운트 +1
666의 존재를 아주 깔끔하게 확인해주셨네요! 아주 좋습니다👍👍

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/1436.cpp
> +    }
이 부분은 함수화해주셔도 좋을 것 같아요!

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/14620.cpp
> +}
함수화 아주 좋습니다👍👍

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/14620.cpp
> +                    cout << x[2] << ", " << y[2] << "\n\n";
P1. 디버깅 용 코드를 그대로 제출해주신 것 같습니다...! 한 번 확인해주세요😂

2023-09-17 11:05 UTC, kwakrhkr59 commented on 04_브루트포스/14620.cpp
> +                    y[2]=i;
P1. 꽃 심는 위치가 정확하게 브루트포스로 탐색되고 있지 않는 것 같습니다!

2023-09-19 04:18 UTC, kwakrhkr59 approved these changes
안녕하세요 은솜님! 재제출 확인되셨습니다 수고 많으셨습니다😊 이제 머지하셔도 좋습니다!

2023-09-19 05:38 UTC, merged